void random(){

  //  double TRandom::Gaus(0,0.01)
  TRandom3 rand;//TRandom3 rand : create a generator always initialized with the same default seed
                //Trandom3 rand(0) : create a generator with a new seed generated by a UID(unique identifier)(time, space)
                //or you can do rand.SetSeed(0) to be time dependently random.
  rand.SetSeed(0);//SetSeed(long). 0 : time random(UID)
  for(int i = 0 ; i < 1 ; i++){


    double ran = rand.Gaus(0, 0.01);
    //    double ran = rand.Gaus(0, 0.001);
    cout<<"ran : "<<ran<<endl;
  }

}
